management:
  endpoints:
    web:
      exposure:
        include: info, health #默认只开放了info和health端点
      #不暴露端点
#        exclude: env #将env端点隐藏起来，不对外暴露
        #暴露的端点
#        include: "*" #将所有端点都暴露出来
  endpoint:
    health:
      show-details: always
