server:
  port: 8082

spring:
  application:
    name: dubbo-service-consumer

dubbo:
  application:
    id: dubbo-service-consumer
    name: dubbo-service-consumer
  registry:
    id: registry-server
    address: localhost:2181
    protocol: zookeeper
